[package]
name = "radix-leptos-aspect-ratio"
description = "Leptos port of Radix Aspect Ratio."
homepage = "https://radix.rustforweb.org/primitives/components/aspect-ratio.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
leptos-node-ref.workspace = true
radix-leptos-primitive.workspace = true
