[package]
name = "radix-leptos-progress"
description = "Leptos port of Radix Progress."
homepage = "https://radix.rustforweb.org/primitives/components/progress.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
