[package]
name = "radix-leptos-dismissable-layer"
description = "Leptos port of Radix Dismissable Layer."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
indexmap.workspace = true
leptos.workspace = true
leptos-maybe-callback.workspace = true
leptos-node-ref.workspace = true
leptos-use.workspace = true
radix-leptos-primitive.workspace = true
radix-leptos-compose-refs.workspace = true
radix-leptos-use-escape-keydown.workspace = true
send_wrapper.workspace = true
serde.workspace = true
serde-wasm-bindgen.workspace = true
wasm-bindgen.workspace = true
