[package]
name = "radix-leptos-focus-guards"
description = "Leptos port of Radix Focus Guards."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
web-sys = { workspace = true, features = ["Document", "NodeList"] }
