[package]
name = "radix-leptos-label"
description = "Leptos port of Radix Label."
homepage = "https://radix.rustforweb.org/primitives/components/label.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
leptos-maybe-callback.workspace = true
leptos-node-ref.workspace = true
radix-leptos-primitive = { path = "../primitive", version = "0.0.2" }
web-sys.workspace = true
