//! Yew port of [Radix Icons](https://www.radix-ui.com/icons).
//!
//! Radix Icons is a crisp set of 15x15 icons.
//!
//! See [the Rust Radix book](https://radix.rustforweb.org/icons/index.html) for more documenation.

#![allow(ambiguous_glob_reexports)]

mod accessibility_icon;
mod activity_log_icon;
mod align_baseline_icon;
mod align_bottom_icon;
mod align_center_horizontally_icon;
mod align_center_vertically_icon;
mod align_left_icon;
mod align_right_icon;
mod align_top_icon;
mod all_sides_icon;
mod angle_icon;
mod archive_icon;
mod arrow_bottom_left_icon;
mod arrow_bottom_right_icon;
mod arrow_down_icon;
mod arrow_left_icon;
mod arrow_right_icon;
mod arrow_top_left_icon;
mod arrow_top_right_icon;
mod arrow_up_icon;
mod aspect_ratio_icon;
mod avatar_icon;
mod backpack_icon;
mod badge_icon;
mod bar_chart_icon;
mod bell_icon;
mod blending_mode_icon;
mod bookmark_filled_icon;
mod bookmark_icon;
mod border_all_icon;
mod border_bottom_icon;
mod border_dashed_icon;
mod border_dotted_icon;
mod border_left_icon;
mod border_none_icon;
mod border_right_icon;
mod border_solid_icon;
mod border_split_icon;
mod border_style_icon;
mod border_top_icon;
mod border_width_icon;
mod box_icon;
mod box_model_icon;
mod button_icon;
mod calendar_icon;
mod camera_icon;
mod card_stack_icon;
mod card_stack_minus_icon;
mod card_stack_plus_icon;
mod caret_down_icon;
mod caret_left_icon;
mod caret_right_icon;
mod caret_sort_icon;
mod caret_up_icon;
mod chat_bubble_icon;
mod check_circled_icon;
mod check_icon;
mod checkbox_icon;
mod chevron_down_icon;
mod chevron_left_icon;
mod chevron_right_icon;
mod chevron_up_icon;
mod circle_backslash_icon;
mod circle_icon;
mod clipboard_copy_icon;
mod clipboard_icon;
mod clock_icon;
mod code_icon;
mod codesandbox_logo_icon;
mod color_wheel_icon;
mod column_spacing_icon;
mod columns_icon;
mod commit_icon;
mod component_1_icon;
mod component_2_icon;
mod component_boolean_icon;
mod component_instance_icon;
mod component_none_icon;
mod component_placeholder_icon;
mod container_icon;
mod cookie_icon;
mod copy_icon;
mod corner_bottom_left_icon;
mod corner_bottom_right_icon;
mod corner_top_left_icon;
mod corner_top_right_icon;
mod corners_icon;
mod countdown_timer_icon;
mod counter_clockwise_clock_icon;
mod crop_icon;
mod cross_1_icon;
mod cross_2_icon;
mod cross_circled_icon;
mod crosshair_1_icon;
mod crosshair_2_icon;
mod crumpled_paper_icon;
mod cube_icon;
mod cursor_arrow_icon;
mod cursor_text_icon;
mod dash_icon;
mod dashboard_icon;
mod desktop_icon;
mod dimensions_icon;
mod disc_icon;
mod discord_logo_icon;
mod divider_horizontal_icon;
mod divider_vertical_icon;
mod dot_filled_icon;
mod dot_icon;
mod dots_horizontal_icon;
mod dots_vertical_icon;
mod double_arrow_down_icon;
mod double_arrow_left_icon;
mod double_arrow_right_icon;
mod double_arrow_up_icon;
mod download_icon;
mod drag_handle_dots_1_icon;
mod drag_handle_dots_2_icon;
mod drag_handle_horizontal_icon;
mod drag_handle_vertical_icon;
mod drawing_pin_filled_icon;
mod drawing_pin_icon;
mod dropdown_menu_icon;
mod enter_full_screen_icon;
mod enter_icon;
mod envelope_closed_icon;
mod envelope_open_icon;
mod eraser_icon;
mod exclamation_triangle_icon;
mod exit_full_screen_icon;
mod exit_icon;
mod external_link_icon;
mod eye_closed_icon;
mod eye_none_icon;
mod eye_open_icon;
mod face_icon;
mod figma_logo_icon;
mod file_icon;
mod file_minus_icon;
mod file_plus_icon;
mod file_text_icon;
mod font_bold_icon;
mod font_family_icon;
mod font_italic_icon;
mod font_roman_icon;
mod font_size_icon;
mod font_style_icon;
mod frame_icon;
mod framer_logo_icon;
mod gear_icon;
mod github_logo_icon;
mod globe_icon;
mod grid_icon;
mod group_icon;
mod half_1_icon;
mod half_2_icon;
mod hamburger_menu_icon;
mod hand_icon;
mod heading_icon;
mod heart_filled_icon;
mod heart_icon;
mod height_icon;
mod hobby_knife_icon;
mod home_icon;
mod iconjar_logo_icon;
mod id_card_icon;
mod image_icon;
mod info_circled_icon;
mod input_icon;
mod instagram_logo_icon;
mod keyboard_icon;
mod lap_timer_icon;
mod laptop_icon;
mod layers_icon;
mod layout_icon;
mod letter_case_capitalize_icon;
mod letter_case_lowercase_icon;
mod letter_case_toggle_icon;
mod letter_case_uppercase_icon;
mod letter_spacing_icon;
mod lightning_bolt_icon;
mod line_height_icon;
mod link_1_icon;
mod link_2_icon;
mod link_break_1_icon;
mod link_break_2_icon;
mod link_none_1_icon;
mod link_none_2_icon;
mod linkedin_logo_icon;
mod list_bullet_icon;
mod lock_closed_icon;
mod lock_open_1_icon;
mod lock_open_2_icon;
mod loop_icon;
mod magic_wand_icon;
mod magnifying_glass_icon;
mod margin_icon;
mod mask_off_icon;
mod mask_on_icon;
mod minus_circled_icon;
mod minus_icon;
mod mix_icon;
mod mixer_horizontal_icon;
mod mixer_vertical_icon;
mod mobile_icon;
mod modulz_logo_icon;
mod moon_icon;
mod move_icon;
mod notion_logo_icon;
mod opacity_icon;
mod open_in_new_window_icon;
mod overline_icon;
mod padding_icon;
mod paper_plane_icon;
mod pause_icon;
mod pencil_1_icon;
mod pencil_2_icon;
mod person_icon;
mod pie_chart_icon;
mod pilcrow_icon;
mod pin_bottom_icon;
mod pin_left_icon;
mod pin_right_icon;
mod pin_top_icon;
mod play_icon;
mod plus_circled_icon;
mod plus_icon;
mod question_mark_circled_icon;
mod question_mark_icon;
mod quote_icon;
mod radiobutton_icon;
mod reader_icon;
mod reload_icon;
mod reset_icon;
mod resume_icon;
mod rocket_icon;
mod rotate_counter_clockwise_icon;
mod row_spacing_icon;
mod rows_icon;
mod ruler_horizontal_icon;
mod ruler_square_icon;
mod scissors_icon;
mod section_icon;
mod sewing_pin_filled_icon;
mod sewing_pin_icon;
mod shadow_icon;
mod shadow_inner_icon;
mod shadow_none_icon;
mod shadow_outer_icon;
mod share_1_icon;
mod share_2_icon;
mod shuffle_icon;
mod size_icon;
mod sketch_logo_icon;
mod slash_icon;
mod slider_icon;
mod space_between_horizontally_icon;
mod space_between_vertically_icon;
mod space_evenly_horizontally_icon;
mod space_evenly_vertically_icon;
mod speaker_loud_icon;
mod speaker_moderate_icon;
mod speaker_off_icon;
mod speaker_quiet_icon;
mod square_icon;
mod stack_icon;
mod star_filled_icon;
mod star_icon;
mod stitches_logo_icon;
mod stop_icon;
mod stopwatch_icon;
mod stretch_horizontally_icon;
mod stretch_vertically_icon;
mod strikethrough_icon;
mod sun_icon;
mod switch_icon;
mod symbol_icon;
mod table_icon;
mod target_icon;
mod text_align_bottom_icon;
mod text_align_center_icon;
mod text_align_justify_icon;
mod text_align_left_icon;
mod text_align_middle_icon;
mod text_align_right_icon;
mod text_align_top_icon;
mod text_icon;
mod text_none_icon;
mod thick_arrow_down_icon;
mod thick_arrow_left_icon;
mod thick_arrow_right_icon;
mod thick_arrow_up_icon;
mod timer_icon;
mod tokens_icon;
mod track_next_icon;
mod track_previous_icon;
mod transform_icon;
mod transparency_grid_icon;
mod trash_icon;
mod triangle_down_icon;
mod triangle_left_icon;
mod triangle_right_icon;
mod triangle_up_icon;
mod twitter_logo_icon;
mod underline_icon;
mod update_icon;
mod upload_icon;
mod value_icon;
mod value_none_icon;
mod vercel_logo_icon;
mod video_icon;
mod view_grid_icon;
mod view_horizontal_icon;
mod view_none_icon;
mod view_vertical_icon;
mod width_icon;
mod zoom_in_icon;
mod zoom_out_icon;

pub use accessibility_icon::*;
pub use activity_log_icon::*;
pub use align_baseline_icon::*;
pub use align_bottom_icon::*;
pub use align_center_horizontally_icon::*;
pub use align_center_vertically_icon::*;
pub use align_left_icon::*;
pub use align_right_icon::*;
pub use align_top_icon::*;
pub use all_sides_icon::*;
pub use angle_icon::*;
pub use archive_icon::*;
pub use arrow_bottom_left_icon::*;
pub use arrow_bottom_right_icon::*;
pub use arrow_down_icon::*;
pub use arrow_left_icon::*;
pub use arrow_right_icon::*;
pub use arrow_top_left_icon::*;
pub use arrow_top_right_icon::*;
pub use arrow_up_icon::*;
pub use aspect_ratio_icon::*;
pub use avatar_icon::*;
pub use backpack_icon::*;
pub use badge_icon::*;
pub use bar_chart_icon::*;
pub use bell_icon::*;
pub use blending_mode_icon::*;
pub use bookmark_filled_icon::*;
pub use bookmark_icon::*;
pub use border_all_icon::*;
pub use border_bottom_icon::*;
pub use border_dashed_icon::*;
pub use border_dotted_icon::*;
pub use border_left_icon::*;
pub use border_none_icon::*;
pub use border_right_icon::*;
pub use border_solid_icon::*;
pub use border_split_icon::*;
pub use border_style_icon::*;
pub use border_top_icon::*;
pub use border_width_icon::*;
pub use box_icon::*;
pub use box_model_icon::*;
pub use button_icon::*;
pub use calendar_icon::*;
pub use camera_icon::*;
pub use card_stack_icon::*;
pub use card_stack_minus_icon::*;
pub use card_stack_plus_icon::*;
pub use caret_down_icon::*;
pub use caret_left_icon::*;
pub use caret_right_icon::*;
pub use caret_sort_icon::*;
pub use caret_up_icon::*;
pub use chat_bubble_icon::*;
pub use check_circled_icon::*;
pub use check_icon::*;
pub use checkbox_icon::*;
pub use chevron_down_icon::*;
pub use chevron_left_icon::*;
pub use chevron_right_icon::*;
pub use chevron_up_icon::*;
pub use circle_backslash_icon::*;
pub use circle_icon::*;
pub use clipboard_copy_icon::*;
pub use clipboard_icon::*;
pub use clock_icon::*;
pub use code_icon::*;
pub use codesandbox_logo_icon::*;
pub use color_wheel_icon::*;
pub use column_spacing_icon::*;
pub use columns_icon::*;
pub use commit_icon::*;
pub use component_1_icon::*;
pub use component_2_icon::*;
pub use component_boolean_icon::*;
pub use component_instance_icon::*;
pub use component_none_icon::*;
pub use component_placeholder_icon::*;
pub use container_icon::*;
pub use cookie_icon::*;
pub use copy_icon::*;
pub use corner_bottom_left_icon::*;
pub use corner_bottom_right_icon::*;
pub use corner_top_left_icon::*;
pub use corner_top_right_icon::*;
pub use corners_icon::*;
pub use countdown_timer_icon::*;
pub use counter_clockwise_clock_icon::*;
pub use crop_icon::*;
pub use cross_1_icon::*;
pub use cross_2_icon::*;
pub use cross_circled_icon::*;
pub use crosshair_1_icon::*;
pub use crosshair_2_icon::*;
pub use crumpled_paper_icon::*;
pub use cube_icon::*;
pub use cursor_arrow_icon::*;
pub use cursor_text_icon::*;
pub use dash_icon::*;
pub use dashboard_icon::*;
pub use desktop_icon::*;
pub use dimensions_icon::*;
pub use disc_icon::*;
pub use discord_logo_icon::*;
pub use divider_horizontal_icon::*;
pub use divider_vertical_icon::*;
pub use dot_filled_icon::*;
pub use dot_icon::*;
pub use dots_horizontal_icon::*;
pub use dots_vertical_icon::*;
pub use double_arrow_down_icon::*;
pub use double_arrow_left_icon::*;
pub use double_arrow_right_icon::*;
pub use double_arrow_up_icon::*;
pub use download_icon::*;
pub use drag_handle_dots_1_icon::*;
pub use drag_handle_dots_2_icon::*;
pub use drag_handle_horizontal_icon::*;
pub use drag_handle_vertical_icon::*;
pub use drawing_pin_filled_icon::*;
pub use drawing_pin_icon::*;
pub use dropdown_menu_icon::*;
pub use enter_full_screen_icon::*;
pub use enter_icon::*;
pub use envelope_closed_icon::*;
pub use envelope_open_icon::*;
pub use eraser_icon::*;
pub use exclamation_triangle_icon::*;
pub use exit_full_screen_icon::*;
pub use exit_icon::*;
pub use external_link_icon::*;
pub use eye_closed_icon::*;
pub use eye_none_icon::*;
pub use eye_open_icon::*;
pub use face_icon::*;
pub use figma_logo_icon::*;
pub use file_icon::*;
pub use file_minus_icon::*;
pub use file_plus_icon::*;
pub use file_text_icon::*;
pub use font_bold_icon::*;
pub use font_family_icon::*;
pub use font_italic_icon::*;
pub use font_roman_icon::*;
pub use font_size_icon::*;
pub use font_style_icon::*;
pub use frame_icon::*;
pub use framer_logo_icon::*;
pub use gear_icon::*;
pub use github_logo_icon::*;
pub use globe_icon::*;
pub use grid_icon::*;
pub use group_icon::*;
pub use half_1_icon::*;
pub use half_2_icon::*;
pub use hamburger_menu_icon::*;
pub use hand_icon::*;
pub use heading_icon::*;
pub use heart_filled_icon::*;
pub use heart_icon::*;
pub use height_icon::*;
pub use hobby_knife_icon::*;
pub use home_icon::*;
pub use iconjar_logo_icon::*;
pub use id_card_icon::*;
pub use image_icon::*;
pub use info_circled_icon::*;
pub use input_icon::*;
pub use instagram_logo_icon::*;
pub use keyboard_icon::*;
pub use lap_timer_icon::*;
pub use laptop_icon::*;
pub use layers_icon::*;
pub use layout_icon::*;
pub use letter_case_capitalize_icon::*;
pub use letter_case_lowercase_icon::*;
pub use letter_case_toggle_icon::*;
pub use letter_case_uppercase_icon::*;
pub use letter_spacing_icon::*;
pub use lightning_bolt_icon::*;
pub use line_height_icon::*;
pub use link_1_icon::*;
pub use link_2_icon::*;
pub use link_break_1_icon::*;
pub use link_break_2_icon::*;
pub use link_none_1_icon::*;
pub use link_none_2_icon::*;
pub use linkedin_logo_icon::*;
pub use list_bullet_icon::*;
pub use lock_closed_icon::*;
pub use lock_open_1_icon::*;
pub use lock_open_2_icon::*;
pub use loop_icon::*;
pub use magic_wand_icon::*;
pub use magnifying_glass_icon::*;
pub use margin_icon::*;
pub use mask_off_icon::*;
pub use mask_on_icon::*;
pub use minus_circled_icon::*;
pub use minus_icon::*;
pub use mix_icon::*;
pub use mixer_horizontal_icon::*;
pub use mixer_vertical_icon::*;
pub use mobile_icon::*;
pub use modulz_logo_icon::*;
pub use moon_icon::*;
pub use move_icon::*;
pub use notion_logo_icon::*;
pub use opacity_icon::*;
pub use open_in_new_window_icon::*;
pub use overline_icon::*;
pub use padding_icon::*;
pub use paper_plane_icon::*;
pub use pause_icon::*;
pub use pencil_1_icon::*;
pub use pencil_2_icon::*;
pub use person_icon::*;
pub use pie_chart_icon::*;
pub use pilcrow_icon::*;
pub use pin_bottom_icon::*;
pub use pin_left_icon::*;
pub use pin_right_icon::*;
pub use pin_top_icon::*;
pub use play_icon::*;
pub use plus_circled_icon::*;
pub use plus_icon::*;
pub use question_mark_circled_icon::*;
pub use question_mark_icon::*;
pub use quote_icon::*;
pub use radiobutton_icon::*;
pub use reader_icon::*;
pub use reload_icon::*;
pub use reset_icon::*;
pub use resume_icon::*;
pub use rocket_icon::*;
pub use rotate_counter_clockwise_icon::*;
pub use row_spacing_icon::*;
pub use rows_icon::*;
pub use ruler_horizontal_icon::*;
pub use ruler_square_icon::*;
pub use scissors_icon::*;
pub use section_icon::*;
pub use sewing_pin_filled_icon::*;
pub use sewing_pin_icon::*;
pub use shadow_icon::*;
pub use shadow_inner_icon::*;
pub use shadow_none_icon::*;
pub use shadow_outer_icon::*;
pub use share_1_icon::*;
pub use share_2_icon::*;
pub use shuffle_icon::*;
pub use size_icon::*;
pub use sketch_logo_icon::*;
pub use slash_icon::*;
pub use slider_icon::*;
pub use space_between_horizontally_icon::*;
pub use space_between_vertically_icon::*;
pub use space_evenly_horizontally_icon::*;
pub use space_evenly_vertically_icon::*;
pub use speaker_loud_icon::*;
pub use speaker_moderate_icon::*;
pub use speaker_off_icon::*;
pub use speaker_quiet_icon::*;
pub use square_icon::*;
pub use stack_icon::*;
pub use star_filled_icon::*;
pub use star_icon::*;
pub use stitches_logo_icon::*;
pub use stop_icon::*;
pub use stopwatch_icon::*;
pub use stretch_horizontally_icon::*;
pub use stretch_vertically_icon::*;
pub use strikethrough_icon::*;
pub use sun_icon::*;
pub use switch_icon::*;
pub use symbol_icon::*;
pub use table_icon::*;
pub use target_icon::*;
pub use text_align_bottom_icon::*;
pub use text_align_center_icon::*;
pub use text_align_justify_icon::*;
pub use text_align_left_icon::*;
pub use text_align_middle_icon::*;
pub use text_align_right_icon::*;
pub use text_align_top_icon::*;
pub use text_icon::*;
pub use text_none_icon::*;
pub use thick_arrow_down_icon::*;
pub use thick_arrow_left_icon::*;
pub use thick_arrow_right_icon::*;
pub use thick_arrow_up_icon::*;
pub use timer_icon::*;
pub use tokens_icon::*;
pub use track_next_icon::*;
pub use track_previous_icon::*;
pub use transform_icon::*;
pub use transparency_grid_icon::*;
pub use trash_icon::*;
pub use triangle_down_icon::*;
pub use triangle_left_icon::*;
pub use triangle_right_icon::*;
pub use triangle_up_icon::*;
pub use twitter_logo_icon::*;
pub use underline_icon::*;
pub use update_icon::*;
pub use upload_icon::*;
pub use value_icon::*;
pub use value_none_icon::*;
pub use vercel_logo_icon::*;
pub use video_icon::*;
pub use view_grid_icon::*;
pub use view_horizontal_icon::*;
pub use view_none_icon::*;
pub use view_vertical_icon::*;
pub use width_icon::*;
pub use zoom_in_icon::*;
pub use zoom_out_icon::*;
