[package]
name = "radix-leptos-themes"
description = "Leptos port of Radix Themes."
homepage = "https://radix.rustforweb.org/themes/index.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
radix-leptos-direction = { path = "../../primitives/leptos/direction", version = "0.0.2" }
leptos.workspace = true
