[package]
name = "radix-yew-switch"
description = "Yew port of Radix Switch."
homepage = "https://radix.rustforweb.org/primitives/components/switch.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
radix-yew-primitive.workspace = true
radix-yew-use-controllable-state.workspace = true
radix-yew-use-previous.workspace = true
radix-yew-use-size.workspace = true
web-sys = { workspace = true, features = ["Event", "EventInit"] }
yew.workspace = true
yew-struct-component.workspace = true
yew-style.workspace = true
