[package]
name = "radix-leptos-avatar"
description = "Leptos port of Radix Avatar."
homepage = "https://radix.rustforweb.org/primitives/components/avatar.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
leptos-node-ref.workspace = true
leptos-maybe-callback.workspace = true
leptos-use.workspace = true
radix-leptos-primitive = { path = "../primitive", version = "0.0.2" }
radix-leptos-context = { path = "../context", version = "0.0.2" }
web-sys.workspace = true
